# Biologic monorepo — единый Makefile для backend (uv, Python 3.11) и frontend (bun).
# Backend-цели (be-*) выполняются внутри backend/, frontend-цели (fe-*) — внутри frontend/.
# Агрегаты (lint/test/format/...) вызывают обе подсистемы.

# --- backend vars (из бывшего backend/Makefile) ---
SEED_ARGS ?=
ANALYZE_QUERY_ARGS ?= --seed-profile perf-lite --truncate --database-url postgresql://biologic:biologic@localhost:5433/biologic
K6_BASE_URL ?= http://localhost:8080/api/v1
K6_CONTEXTS ?= workflow
K6_ALL_JSON := $(foreach c,$(K6_CONTEXTS),reports/k6/$(c)-results.json)

.PHONY: help install lint format test typecheck build e2e sdk-generate \
        be-dev be-test be-lint be-format be-audit be-seed-data be-analyze-orm-queries \
        be-migrate be-migrate-down be-migration be-migrate-history \
        be-k6-workflow be-k6-scenarios \
        fe-dev fe-preview fe-lint fe-typecheck fe-build fe-test fe-e2e fe-format fe-sdk-generate

help:
	@echo "Biologic monorepo"
	@echo "  make install       backend: uv sync  +  frontend: bun install"
	@echo "  make lint          be-lint + fe-lint (ruff+mypy / eslint)"
	@echo "  make test          be-test + fe-test (pytest / bun test)"
	@echo "  make fe-preview    fe-build + serve production build on :5177"
	@echo "  make format        be-format + fe-format"
	@echo "  make typecheck     fe-typecheck (vue-tsc)"
	@echo "  make build         fe-build (production)"
	@echo "  make e2e           fe-e2e (playwright)"
	@echo "  make sdk-generate  regenerate FE SDK from a running backend (:8080)"
	@echo "  make be-migrate            apply migrations (alembic upgrade head)"
	@echo "  make be-migration m=\"...\"  create a new autogenerated migration"
	@echo "  make be-migrate-down       revert the last migration (downgrade -1)"
	@echo "  backend: be-dev be-test be-lint be-format be-audit be-seed-data be-k6-scenarios"
	@echo "  frontend: fe-dev fe-lint fe-typecheck fe-build fe-test fe-e2e"

# --- aggregates ---
install:
	cd backend && uv sync --all-extras
	cd frontend && bun install

lint: be-lint fe-lint
format: be-format fe-format
test: be-test fe-test
typecheck: fe-typecheck
build: fe-build
e2e: fe-e2e
sdk-generate: fe-sdk-generate

# --- backend (бывший backend/Makefile; выполняется в backend/) ---
be-dev:
	cd backend && uv run uvicorn src.main:app --reload --host 0.0.0.0 --port 8080 --timeout-graceful-shutdown 10

be-test:
	cd backend && uv run pytest -v

be-lint:
	cd backend && uv run ruff check src tests
	cd backend && uv run mypy src tests

be-format:
	cd backend && uv run ruff format src tests

be-audit:
	cd backend && uv run pip-audit

be-seed-data:
	cd backend && uv run python -m scripts.seed_test_data $(SEED_ARGS)

# --- миграции (alembic; нужна поднятая БД — APP_DATABASE_URL из backend/.env) ---
be-migrate:
	cd backend && uv run alembic upgrade head

be-migrate-down:
	cd backend && uv run alembic downgrade -1

# Создать новую миграцию из diff моделей: make be-migration m="описание"
be-migration:
	@test -n "$(m)" || { echo 'usage: make be-migration m="описание"'; exit 1; }
	cd backend && uv run alembic revision --autogenerate -m "$(m)"

be-migrate-history:
	cd backend && uv run alembic history --verbose

be-analyze-orm-queries:
	cd backend && uv run python -m scripts.analyze_orm_query_plans $(ANALYZE_QUERY_ARGS)

# k6: нужен запущенный API (make be-dev) на мигрированной БД. Отчёты — в backend/reports/k6/,
# прогон падает при нарушении порога (checks rate==1.00).
be-k6-workflow:
	cd backend && mkdir -p reports/k6 && \
		BASE_URL=$(K6_BASE_URL) k6 run --out json=reports/k6/workflow-results.json tests/k6/scenarios/workflow/index.js && \
		uv run python -m scripts.k6_report_visual reports/k6/workflow-results.json --title "Biologic — Workflow" --base-url $(K6_BASE_URL)

be-k6-scenarios:
	cd backend && mkdir -p reports/k6; rc=0; for ctx in $(K6_CONTEXTS); do \
		echo "── k6 scenarios: $$ctx ──"; \
		BASE_URL=$(K6_BASE_URL) k6 run --out json=reports/k6/$$ctx-results.json tests/k6/scenarios/$$ctx/index.js || rc=1; \
	done; \
	echo "── building combined report ──"; \
	uv run python -m scripts.k6_report_visual $(K6_ALL_JSON) -o reports/k6/all-results.html --title "Biologic — All Scenarios" --base-url $(K6_BASE_URL); \
	exit $$rc

# --- frontend (выполняется в frontend/) ---
fe-dev:
	cd frontend && bun run dev

fe-lint:
	cd frontend && bun run lint

fe-typecheck:
	cd frontend && bun run typecheck

fe-build:
	cd frontend && bun run build

fe-preview: fe-build
	cd frontend && bun run preview -- --port 5177

fe-test:
	cd frontend && bun test tests/shared

fe-e2e:
	cd frontend && bun run test:e2e

fe-format:
	cd frontend && bun run lint --fix || true

fe-sdk-generate:
	cd frontend && bun run sdk:generate
